### ISSUE TITLE
please don't mingle with bitbns timestamps error

### ISSUE THREAD

**Issue by Wicpar** [bitbns-official/bitbns-rest-endpoints#1]
Hi,

I am implementing this api in rust, and I am getting this when i use v1 post requests
```json
{"data":null,"status":0,"error":"please don't mingle with bitbns timestamps","code":401}
```

on v2 posts i only get "something went wrong" without an http error code, but that is likely because i don't have the balance for an order

What am i doing wrong ? I checked that i send the proper information, the keys are right, etc...

**Comment by Wicpar** [comment]
Fixed, i had the body for the payload as an object and not as a string. The errors really aren't clear. Also don't be fooled, the bodies are not url encoded despite what the headers say.

**Comment by dgnk007** [comment]
I am to having same problem. How to solve this issue
